export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function AuthLayout({ children }) {
  return (
    <div className='flex h-screen w-full items-center justify-center'>
      {children}
    </div>
  )
}
